[input]
base_directory = "/Users/scott_carvalho/projects/Scarvy.github.io/output"
html_selector = "main"

[[input.files]]
path = "pages/about.html"
url = "/pages/about.html"
title = "About"

[[input.files]]
path = "pages/books.html"
url = "/pages/books.html"
title = "Books"

[[input.files]]
path = "pages/publications.html"
url = "/pages/publications.html"
title = "Publications"

[[input.files]]
path = "pages/resume.html"
url = "/pages/resume.html"
title = "Resume"

[[input.files]]
path = "pages/talks.html"
url = "/pages/talks.html"
title = "Talks"