[input]
base_directory = "/Users/scott_carvalho/projects/Scarvy.github.io/output"
html_selector = "main"

[[input.files]]
path = "pages/about.html"
url = "/pages/about.html"
title = "About"

[[input.files]]
path = "pages/books.html"
url = "/pages/books.html"
title = "Books"

[[input.files]]
path = "intergating-esg-considerations-into-securties-lending.html"
url = "/intergating-esg-considerations-into-securties-lending.html"
title = "Intergating ESG considerations into Securties Lending"